stages:
  - style
  - build
  - test
  - deploy

codestyle_job:
  stage: style
  tags:
    - build
  script:
    - cp materials/linters/.clang-format src/cat
    - cp materials/linters/.clang-format src/grep
    - cd src/cat
    - clang-format --Werror -n *.[ch]
    - cd ../grep
    - clang-format --Werror -n *.[ch]
  after_script:
    - chmod +x src/bot.sh
    - bash src/bot.sh

build_job:
  stage: build
  tags:
    - build
  script:
    - cd src/cat
    - make build
    - cd ../grep
    - make build
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days
  after_script:
    - chmod +x src/bot.sh
    - bash src/bot.sh

test_job:
  stage: test
  tags: 
    - build
  script:
    - cd src/cat
    - make test
    - cd ../grep
    - make test
  when: on_success
  after_script:
    - chmod +x src/bot.sh
    - bash src/bot.sh

deploy_job:
  stage: deploy
  tags:
    - build
  when: manual
  script:
    - chmod +x src/deploy.sh
    - bash src/deploy.sh
  after_script:
    - chmod +x src/bot.sh
    - bash src/bot.sh